const lala = document.querySelector(".lala");
const swipercontainer = document.querySelector(".swiper-container");
const infouls = document.querySelectorAll(".info ul");
const clickme = document.querySelector(".clickme");
const navlinks = document.querySelectorAll(".bottomnav ul li");
const logo = document.querySelector(".nav .logo");
const proyectos = document.querySelector(".proyects");
const profiletext = document.querySelector(".profiletext");
const proyectoslinks = document.querySelectorAll(".proyects ul li");
